### ISSUE TITLE
Implement CameraControls support

### ISSUE THREAD

**Issue by zhusihan-python** [IntQuant/OmniCamera#1]
hello, i notice that the nokhwa support camera setting exposure and [white balance](https://github.com/l1npengtul/nokhwa/blob/043d326583c1ea82e0e8f6f62a267cea954a751a/nokhwa-bindings-windows/src/lib.rs#L241), is there any plan to support that in camerata

**Comment by IntQuant** [comment]
It's planned to support everything nokhwa has, so I'll look into this.

**Comment by IntQuant** [comment]
Added in 0.4.0, however not all controls seem to work yet, at least for me.

**Comment by zhusihan-python** [comment]
> Added in 0.4.0, however not all controls seem to work yet, at least for me.
thank you for your help, there is another question, how to stop or release the opened camera, i found del cam works, is there a elegant way to stop it, i noticed that  Drop is defined in CameraInternal, but not exposed in python Camera class, i guess drop is just like the del in python, right. in nokhwa they provided a stop_stream method, is it better than Drop as the cam instance can be reused (not sure)

**Comment by zhusihan-python** [comment]
> Added in 0.4.0, however not all controls seem to work yet, at least for me.

**Comment by zhusihan-python** [comment]
> Added in 0.4.0, however not all controls seem to work yet, at least for me.

thank you for your help, there is another question, how to stop or release the opened camera, i found del cam works, is there a elegant way to stop it, i noticed that Drop is defined in CameraInternal, but not exposed in python Camera class, i guess drop is just like the del in python, right. in nokhwa they provided a stop_stream method, is it better than Drop as the cam instance can be reused (not sure)

**Comment by IntQuant** [comment]
Camera is closed automatically when it goes out of scope, making `del cam` a good way to close the camera. This also makes it impossible to continue using already closed camera by accident.
As for reusing instances - it's not like anyone is gonna reopen the same camera several times a second, so I don't think it's necessary.
